export const apis={
    projects:{
        allprojects:"/projects"
    },
    tasks:{
        alltasks:"/tasks"
    },
    managers:{
        allmanagers:"/managers"
    },
    employees:{
        allemployees:"/employees"
    },
    holidays:{
        allholidays:"/holidays"
    },
    dmholiday:{
        alldmholidays:"/dmholiday"
    },
    users:{
        allusers:"/users"
    },
    status:{
        allstatus:"/status"
    }
}